# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uLyrYWTuxazZSuMjqN76xmlnHTnGjZ3S
"""

pip install streamlit
import streamlit as st
import pandas as pd

# Load dataset
url = "https://raw.githubusercontent.com/plotly/datasets/master/superstore.csv"
df = pd.read_csv(url)

st.title("Business Dashboard")

region = st.selectbox("Select Region", df['Region'].unique())
filtered = df[df['Region'] == region]

st.write("Total Sales:", filtered['Sales'].sum())
st.write("Profit:", filtered['Profit'].sum())

top_customers = filtered.groupby('Customer Name')['Sales'].sum().sort_values(ascending=False).head(5)
st.bar_chart(top_customers)
streamlit run app.py